# Generated by Django 4.1.2 on 2022-10-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MumbaiExpress', '0002_rename_usern_loginmodel_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactusModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobileno', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
