# Generated by Django 4.1.2 on 2022-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MumbaiExpress', '0003_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
