# Generated by Django 4.1.2 on 2022-10-14 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MumbaiExpress', '0004_alter_contactusmodel_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField()),
                ('mobileno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdertableModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField()),
                ('mobileno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField()),
                ('mobileno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
