# Generated by Django 4.1.2 on 2022-10-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MumbaiExpress', '0005_ordermodel1_ordertablemodel_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderModel1',
        ),
    ]
