# Generated by Django 4.1.2 on 2022-10-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MumbaiExpress', '0006_delete_ordermodel1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.ImageField(blank=True, upload_to='code')),
            ],
        ),
    ]
