# Generated by Django 4.1.2 on 2022-10-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MumbaiExpress', '0007_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Ordersqr',
        ),
    ]
